extends Node3D

var secret

func _ready():
	secret = randi() % 10000
	#$".."/CombiCode.mesh.text = "%04d" % combination #met leading 0'en

func _on_static_body_3d_input_event(camera, event, position, normal, shape_idx):
	if event is InputEventMouseButton and event.is_action_pressed("interact"):
		$Kast/Drawer.position.z = abs($Kast/Drawer.position.z - 1.0)


func _on_sleutel_input_event(camera, event, position, normal, shape_idx):
	if event is InputEventMouseButton and event.is_action_pressed("interact"):
		$Kast/Drawer/Sleutel.visible = false
		get_node("../Player").has_key = true
