extends Node3D

var open = false
var sound_open = preload("res://Audio/drawer-open.wav")
var sound_close = preload("res://Audio/drawer-close.wav")

func _on_static_body_3d_input_event(_camera, event, _position, _normal, _shape_idx):
	if event is InputEventMouseButton and event.is_action_pressed("interact"):
		if open:
			$Kast/Drawer/DrawerSound.stream = sound_close
		else:
			$Kast/Drawer/DrawerSound.stream = sound_open
		open = !open
		$Kast/Drawer.position.z = abs($Kast/Drawer.position.z - 1.0) 
		$Kast/Drawer/DrawerSound.playing = true


func _on_sleutel_input_event(_camera, event, _position, _normal, _shape_idx):
	if event is InputEventMouseButton and event.is_action_pressed("interact"):
		$Kast/Drawer/Sleutel.visible = false
		get_node("../Player").has_key = true
		get_node("../Player/Pickup").playing = true
		$"../Gui".add_item(preload("res://Objects/sleutel.tscn").instantiate())
